minimum_pre_commit_version: "2.9.0"
repos:
  - repo: https://github.com/Zac-HD/shed
    rev: 2024.3.1
    hooks:
      - id: shed
        # TODO(pcohen): bump to --py310-plus when Talon moves to Python 3.10.
        args: [--refactor, --py39-plus]
        types_or: [python, markdown, rst]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        files: ".*.(md|json|yaml)$"
  - repo: https://github.com/ikamensh/flynt/
    rev: "1.0.1"
    hooks:
      - id: flynt
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs
        types: [file]
        files: \.talon$
        args: ["--whitespaces-count=4"]
  - repo: https://github.com/wenkokke/talonfmt
    rev: 1.10.2
    hooks:
      - id: talonfmt
        args: ["--in-place", "--max-line-width=88"]
